import type { Severity } from '@/types'

interface OBD2CodeEntry {
  code: string
  name: string
  description: string
  severity: Severity
}

export const OBD2_CODES: Record<string, OBD2CodeEntry> = {
  P0100: { code: 'P0100', name: 'Mass Air Flow Sensor Circuit Malfunction', description: 'The mass air flow sensor circuit is not functioning properly.', severity: 'WARNING' },
  P0101: { code: 'P0101', name: 'Mass Air Flow Sensor Circuit Range/Performance', description: 'MAF sensor output is outside expected range.', severity: 'WARNING' },
  P0102: { code: 'P0102', name: 'Mass Air Flow Sensor Circuit Low Input', description: 'MAF sensor is reading lower than expected.', severity: 'WARNING' },
  P0103: { code: 'P0103', name: 'Mass Air Flow Sensor Circuit High Input', description: 'MAF sensor is reading higher than expected.', severity: 'WARNING' },
  P0104: { code: 'P0104', name: 'Mass Air Flow Sensor Circuit Intermittent', description: 'MAF sensor signal is cutting in and out.', severity: 'WARNING' },
  P0105: { code: 'P0105', name: 'Manifold Absolute Pressure Sensor Circuit Malfunction', description: 'MAP sensor circuit fault detected.', severity: 'WARNING' },
  P0110: { code: 'P0110', name: 'Intake Air Temperature Sensor Circuit Malfunction', description: 'IAT sensor circuit is faulty.', severity: 'INFO' },
  P0111: { code: 'P0111', name: 'Intake Air Temperature Sensor Circuit Range/Performance', description: 'IAT sensor reading is outside normal range.', severity: 'INFO' },
  P0112: { code: 'P0112', name: 'Intake Air Temperature Sensor Circuit Low Input', description: 'IAT sensor voltage too low.', severity: 'INFO' },
  P0113: { code: 'P0113', name: 'Intake Air Temperature Sensor Circuit High Input', description: 'IAT sensor voltage too high.', severity: 'INFO' },
  P0114: { code: 'P0114', name: 'Intake Air Temperature Sensor Circuit Intermittent', description: 'IAT sensor signal intermittent.', severity: 'INFO' },
  P0115: { code: 'P0115', name: 'Engine Coolant Temperature Sensor Circuit Malfunction', description: 'ECT sensor circuit fault.', severity: 'WARNING' },
  P0120: { code: 'P0120', name: 'Throttle Position Sensor Circuit Malfunction', description: 'TPS sensor A circuit fault.', severity: 'WARNING' },
  P0121: { code: 'P0121', name: 'Throttle Position Sensor Circuit Range/Performance', description: 'TPS sensor A out of range.', severity: 'WARNING' },
  P0122: { code: 'P0122', name: 'Throttle Position Sensor Circuit Low Input', description: 'TPS sensor A voltage too low.', severity: 'WARNING' },
  P0123: { code: 'P0123', name: 'Throttle Position Sensor Circuit High Input', description: 'TPS sensor A voltage too high.', severity: 'WARNING' },
  P0124: { code: 'P0124', name: 'Throttle Position Sensor Circuit Intermittent', description: 'TPS sensor A intermittent signal.', severity: 'WARNING' },
  P0125: { code: 'P0125', name: 'Insufficient Coolant Temperature for Closed Loop Fuel Control', description: 'Engine not reaching operating temperature.', severity: 'WARNING' },
  P0130: { code: 'P0130', name: 'Oxygen Sensor Circuit Malfunction (Bank 1, Sensor 1)', description: 'Front oxygen sensor circuit fault.', severity: 'WARNING' },
  P0131: { code: 'P0131', name: 'Oxygen Sensor Circuit Low Voltage (Bank 1, Sensor 1)', description: 'Front O2 sensor voltage too low.', severity: 'WARNING' },
  P0132: { code: 'P0132', name: 'Oxygen Sensor Circuit High Voltage (Bank 1, Sensor 1)', description: 'Front O2 sensor voltage too high.', severity: 'WARNING' },
  P0133: { code: 'P0133', name: 'Oxygen Sensor Circuit Slow Response (Bank 1, Sensor 1)', description: 'Front O2 sensor responding slowly.', severity: 'WARNING' },
  P0134: { code: 'P0134', name: 'Oxygen Sensor Circuit No Activity Detected (Bank 1, Sensor 1)', description: 'Front O2 sensor not responding.', severity: 'WARNING' },
  P0135: { code: 'P0135', name: 'Oxygen Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)', description: 'Front O2 sensor heater faulty.', severity: 'WARNING' },
  P0136: { code: 'P0136', name: 'Oxygen Sensor Circuit Malfunction (Bank 1, Sensor 2)', description: 'Rear oxygen sensor circuit fault.', severity: 'INFO' },
  P0137: { code: 'P0137', name: 'Oxygen Sensor Circuit Low Voltage (Bank 1, Sensor 2)', description: 'Rear O2 sensor voltage too low.', severity: 'INFO' },
  P0138: { code: 'P0138', name: 'Oxygen Sensor Circuit High Voltage (Bank 1, Sensor 2)', description: 'Rear O2 sensor voltage too high.', severity: 'INFO' },
  P0139: { code: 'P0139', name: 'Oxygen Sensor Circuit Slow Response (Bank 1, Sensor 2)', description: 'Rear O2 sensor slow response.', severity: 'INFO' },
  P0140: { code: 'P0140', name: 'Oxygen Sensor Circuit No Activity (Bank 1, Sensor 2)', description: 'Rear O2 sensor no activity.', severity: 'INFO' },
  P0141: { code: 'P0141', name: 'Oxygen Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)', description: 'Rear O2 sensor heater fault.', severity: 'INFO' },
  P0171: { code: 'P0171', name: 'System Too Lean (Bank 1)', description: 'Engine running lean - too much air or not enough fuel.', severity: 'WARNING' },
  P0172: { code: 'P0172', name: 'System Too Rich (Bank 1)', description: 'Engine running rich - too much fuel.', severity: 'WARNING' },
  P0173: { code: 'P0173', name: 'Fuel Trim Malfunction (Bank 2)', description: 'Fuel trim issue on bank 2.', severity: 'WARNING' },
  P0174: { code: 'P0174', name: 'System Too Lean (Bank 2)', description: 'Engine bank 2 running lean.', severity: 'WARNING' },
  P0175: { code: 'P0175', name: 'System Too Rich (Bank 2)', description: 'Engine bank 2 running rich.', severity: 'WARNING' },
  P0190: { code: 'P0190', name: 'Fuel Rail Pressure Sensor Circuit Malfunction', description: 'Fuel rail pressure sensor circuit fault.', severity: 'CRITICAL' },
  P0191: { code: 'P0191', name: 'Fuel Rail Pressure Sensor Circuit Range/Performance', description: 'Fuel pressure sensor out of range.', severity: 'CRITICAL' },
  P0200: { code: 'P0200', name: 'Injector Circuit Malfunction', description: 'Fuel injector circuit fault.', severity: 'CRITICAL' },
  P0201: { code: 'P0201', name: 'Injector Circuit Malfunction - Cylinder 1', description: 'Cylinder 1 injector circuit fault.', severity: 'CRITICAL' },
  P0202: { code: 'P0202', name: 'Injector Circuit Malfunction - Cylinder 2', description: 'Cylinder 2 injector circuit fault.', severity: 'CRITICAL' },
  P0203: { code: 'P0203', name: 'Injector Circuit Malfunction - Cylinder 3', description: 'Cylinder 3 injector circuit fault.', severity: 'CRITICAL' },
  P0204: { code: 'P0204', name: 'Injector Circuit Malfunction - Cylinder 4', description: 'Cylinder 4 injector circuit fault.', severity: 'CRITICAL' },
  P0205: { code: 'P0205', name: 'Injector Circuit Malfunction - Cylinder 5', description: 'Cylinder 5 injector circuit fault.', severity: 'CRITICAL' },
  P0206: { code: 'P0206', name: 'Injector Circuit Malfunction - Cylinder 6', description: 'Cylinder 6 injector circuit fault.', severity: 'CRITICAL' },
  P0207: { code: 'P0207', name: 'Injector Circuit Malfunction - Cylinder 7', description: 'Cylinder 7 injector circuit fault.', severity: 'CRITICAL' },
  P0208: { code: 'P0208', name: 'Injector Circuit Malfunction - Cylinder 8', description: 'Cylinder 8 injector circuit fault.', severity: 'CRITICAL' },
  P0209: { code: 'P0209', name: 'Injector Circuit Malfunction - Cylinder 9', description: 'Cylinder 9 injector circuit fault.', severity: 'CRITICAL' },
  P0210: { code: 'P0210', name: 'Injector Circuit Malfunction - Cylinder 10', description: 'Cylinder 10 injector circuit fault.', severity: 'CRITICAL' },
  P0211: { code: 'P0211', name: 'Injector Circuit Malfunction - Cylinder 11', description: 'Cylinder 11 injector circuit fault.', severity: 'CRITICAL' },
  P0212: { code: 'P0212', name: 'Injector Circuit Malfunction - Cylinder 12', description: 'Cylinder 12 injector circuit fault.', severity: 'CRITICAL' },
  P0217: { code: 'P0217', name: 'Engine Coolant Over Temperature Condition', description: 'Engine is overheating - stop driving immediately.', severity: 'CRITICAL' },
  P0218: { code: 'P0218', name: 'Transmission Fluid Over Temperature Condition', description: 'Transmission fluid overheating.', severity: 'CRITICAL' },
  P0300: { code: 'P0300', name: 'Random/Multiple Cylinder Misfire Detected', description: 'Multiple cylinders are misfiring randomly.', severity: 'CRITICAL' },
  P0301: { code: 'P0301', name: 'Cylinder 1 Misfire Detected', description: 'Cylinder 1 is misfiring.', severity: 'CRITICAL' },
  P0302: { code: 'P0302', name: 'Cylinder 2 Misfire Detected', description: 'Cylinder 2 is misfiring.', severity: 'CRITICAL' },
  P0303: { code: 'P0303', name: 'Cylinder 3 Misfire Detected', description: 'Cylinder 3 is misfiring.', severity: 'CRITICAL' },
  P0304: { code: 'P0304', name: 'Cylinder 4 Misfire Detected', description: 'Cylinder 4 is misfiring.', severity: 'CRITICAL' },
  P0305: { code: 'P0305', name: 'Cylinder 5 Misfire Detected', description: 'Cylinder 5 is misfiring.', severity: 'CRITICAL' },
  P0306: { code: 'P0306', name: 'Cylinder 6 Misfire Detected', description: 'Cylinder 6 is misfiring.', severity: 'CRITICAL' },
  P0307: { code: 'P0307', name: 'Cylinder 7 Misfire Detected', description: 'Cylinder 7 is misfiring.', severity: 'CRITICAL' },
  P0308: { code: 'P0308', name: 'Cylinder 8 Misfire Detected', description: 'Cylinder 8 is misfiring.', severity: 'CRITICAL' },
  P0309: { code: 'P0309', name: 'Cylinder 9 Misfire Detected', description: 'Cylinder 9 is misfiring.', severity: 'CRITICAL' },
  P0310: { code: 'P0310', name: 'Cylinder 10 Misfire Detected', description: 'Cylinder 10 is misfiring.', severity: 'CRITICAL' },
  P0311: { code: 'P0311', name: 'Cylinder 11 Misfire Detected', description: 'Cylinder 11 is misfiring.', severity: 'CRITICAL' },
  P0312: { code: 'P0312', name: 'Cylinder 12 Misfire Detected', description: 'Cylinder 12 is misfiring.', severity: 'CRITICAL' },
  P0320: { code: 'P0320', name: 'Ignition/Distributor Engine Speed Input Circuit Malfunction', description: 'Ignition speed input fault.', severity: 'CRITICAL' },
  P0325: { code: 'P0325', name: 'Knock Sensor 1 Circuit Malfunction (Bank 1)', description: 'Knock sensor circuit fault on bank 1.', severity: 'WARNING' },
  P0326: { code: 'P0326', name: 'Knock Sensor 1 Circuit Range/Performance (Bank 1)', description: 'Knock sensor 1 out of range.', severity: 'WARNING' },
  P0327: { code: 'P0327', name: 'Knock Sensor 1 Circuit Low Input (Bank 1)', description: 'Knock sensor 1 voltage too low.', severity: 'WARNING' },
  P0328: { code: 'P0328', name: 'Knock Sensor 1 Circuit High Input (Bank 1)', description: 'Knock sensor 1 voltage too high.', severity: 'WARNING' },
  P0335: { code: 'P0335', name: 'Crankshaft Position Sensor A Circuit Malfunction', description: 'Crankshaft position sensor circuit fault - engine may not start.', severity: 'CRITICAL' },
  P0336: { code: 'P0336', name: 'Crankshaft Position Sensor A Circuit Range/Performance', description: 'Crankshaft position sensor out of range.', severity: 'CRITICAL' },
  P0340: { code: 'P0340', name: 'Camshaft Position Sensor A Circuit Malfunction (Bank 1)', description: 'Camshaft position sensor fault.', severity: 'CRITICAL' },
  P0341: { code: 'P0341', name: 'Camshaft Position Sensor A Circuit Range/Performance (Bank 1)', description: 'Cam sensor signal out of range.', severity: 'CRITICAL' },
  P0351: { code: 'P0351', name: 'Ignition Coil A Primary/Secondary Circuit Malfunction', description: 'Ignition coil A circuit fault.', severity: 'CRITICAL' },
  P0352: { code: 'P0352', name: 'Ignition Coil B Primary/Secondary Circuit Malfunction', description: 'Ignition coil B circuit fault.', severity: 'CRITICAL' },
  P0353: { code: 'P0353', name: 'Ignition Coil C Primary/Secondary Circuit Malfunction', description: 'Ignition coil C circuit fault.', severity: 'CRITICAL' },
  P0354: { code: 'P0354', name: 'Ignition Coil D Primary/Secondary Circuit Malfunction', description: 'Ignition coil D circuit fault.', severity: 'CRITICAL' },
  P0355: { code: 'P0355', name: 'Ignition Coil E Primary/Secondary Circuit Malfunction', description: 'Ignition coil E circuit fault.', severity: 'CRITICAL' },
  P0356: { code: 'P0356', name: 'Ignition Coil F Primary/Secondary Circuit Malfunction', description: 'Ignition coil F circuit fault.', severity: 'CRITICAL' },
  P0357: { code: 'P0357', name: 'Ignition Coil G Primary/Secondary Circuit Malfunction', description: 'Ignition coil G circuit fault.', severity: 'CRITICAL' },
  P0358: { code: 'P0358', name: 'Ignition Coil H Primary/Secondary Circuit Malfunction', description: 'Ignition coil H circuit fault.', severity: 'CRITICAL' },
  P0359: { code: 'P0359', name: 'Ignition Coil I Primary/Secondary Circuit Malfunction', description: 'Ignition coil I circuit fault.', severity: 'CRITICAL' },
  P0360: { code: 'P0360', name: 'Ignition Coil J Primary/Secondary Circuit Malfunction', description: 'Ignition coil J circuit fault.', severity: 'CRITICAL' },
  P0361: { code: 'P0361', name: 'Ignition Coil K Primary/Secondary Circuit Malfunction', description: 'Ignition coil K circuit fault.', severity: 'CRITICAL' },
  P0362: { code: 'P0362', name: 'Ignition Coil L Primary/Secondary Circuit Malfunction', description: 'Ignition coil L circuit fault.', severity: 'CRITICAL' },
  P0380: { code: 'P0380', name: 'Glow Plug/Heater Circuit A Malfunction', description: 'Diesel glow plug circuit fault.', severity: 'WARNING' },
  P0381: { code: 'P0381', name: 'Glow Plug/Heater Indicator Circuit Malfunction', description: 'Glow plug indicator circuit fault.', severity: 'WARNING' },
  P0400: { code: 'P0400', name: 'Exhaust Gas Recirculation Flow Malfunction', description: 'EGR system flow fault.', severity: 'WARNING' },
  P0401: { code: 'P0401', name: 'Exhaust Gas Recirculation Insufficient Flow Detected', description: 'EGR flow too low.', severity: 'WARNING' },
  P0402: { code: 'P0402', name: 'Exhaust Gas Recirculation Excessive Flow Detected', description: 'EGR flow too high.', severity: 'WARNING' },
  P0403: { code: 'P0403', name: 'Exhaust Gas Recirculation Circuit Malfunction', description: 'EGR circuit fault.', severity: 'WARNING' },
  P0404: { code: 'P0404', name: 'Exhaust Gas Recirculation Circuit Range/Performance', description: 'EGR circuit out of range.', severity: 'WARNING' },
  P0405: { code: 'P0405', name: 'Exhaust Gas Recirculation Sensor A Circuit Low', description: 'EGR sensor A voltage too low.', severity: 'WARNING' },
  P0406: { code: 'P0406', name: 'Exhaust Gas Recirculation Sensor A Circuit High', description: 'EGR sensor A voltage too high.', severity: 'WARNING' },
  P0410: { code: 'P0410', name: 'Secondary Air Injection System Malfunction', description: 'Air injection system fault.', severity: 'WARNING' },
  P0411: { code: 'P0411', name: 'Secondary Air Injection System Incorrect Flow Detected', description: 'Air injection flow incorrect.', severity: 'WARNING' },
  P0412: { code: 'P0412', name: 'Secondary Air Injection System Switching Valve A Circuit Malfunction', description: 'Air injection valve A fault.', severity: 'WARNING' },
  P0420: { code: 'P0420', name: 'Catalyst System Efficiency Below Threshold (Bank 1)', description: 'Catalytic converter worn or failed on bank 1.', severity: 'WARNING' },
  P0421: { code: 'P0421', name: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)', description: 'Warm-up cat efficiency low.', severity: 'WARNING' },
  P0422: { code: 'P0422', name: 'Main Catalyst Efficiency Below Threshold (Bank 1)', description: 'Main cat efficiency low.', severity: 'WARNING' },
  P0423: { code: 'P0423', name: 'Heated Catalyst Efficiency Below Threshold (Bank 1)', description: 'Heated cat efficiency low.', severity: 'WARNING' },
  P0430: { code: 'P0430', name: 'Catalyst System Efficiency Below Threshold (Bank 2)', description: 'Catalytic converter worn or failed on bank 2.', severity: 'WARNING' },
  P0431: { code: 'P0431', name: 'Warm Up Catalyst Efficiency Below Threshold (Bank 2)', description: 'Bank 2 warm-up cat efficiency low.', severity: 'WARNING' },
  P0440: { code: 'P0440', name: 'Evaporative Emission Control System Malfunction', description: 'EVAP system general fault - often a loose fuel cap.', severity: 'INFO' },
  P0441: { code: 'P0441', name: 'Evaporative Emission Control System Incorrect Purge Flow', description: 'EVAP purge flow incorrect.', severity: 'INFO' },
  P0442: { code: 'P0442', name: 'Evaporative Emission Control System Leak Detected (Small Leak)', description: 'Small fuel vapour leak - check fuel cap first.', severity: 'INFO' },
  P0443: { code: 'P0443', name: 'Evaporative Emission Control System Purge Control Valve Circuit Malfunction', description: 'EVAP purge valve circuit fault.', severity: 'INFO' },
  P0444: { code: 'P0444', name: 'Evaporative Emission Control System Purge Control Valve Circuit Open', description: 'EVAP purge valve circuit open.', severity: 'INFO' },
  P0445: { code: 'P0445', name: 'Evaporative Emission Control System Purge Control Valve Circuit Shorted', description: 'EVAP purge valve shorted.', severity: 'INFO' },
  P0446: { code: 'P0446', name: 'Evaporative Emission Control System Vent Control Circuit Malfunction', description: 'EVAP vent control fault.', severity: 'INFO' },
  P0450: { code: 'P0450', name: 'Evaporative Emission Control System Pressure Sensor Malfunction', description: 'EVAP pressure sensor fault.', severity: 'INFO' },
  P0451: { code: 'P0451', name: 'Evaporative Emission Control System Pressure Sensor Range/Performance', description: 'EVAP pressure sensor out of range.', severity: 'INFO' },
  P0452: { code: 'P0452', name: 'Evaporative Emission Control System Pressure Sensor Low Input', description: 'EVAP pressure sensor low voltage.', severity: 'INFO' },
  P0453: { code: 'P0453', name: 'Evaporative Emission Control System Pressure Sensor High Input', description: 'EVAP pressure sensor high voltage.', severity: 'INFO' },
  P0500: { code: 'P0500', name: 'Vehicle Speed Sensor Malfunction', description: 'Vehicle speed sensor circuit fault.', severity: 'WARNING' },
  P0501: { code: 'P0501', name: 'Vehicle Speed Sensor Range/Performance', description: 'Speed sensor out of range.', severity: 'WARNING' },
  P0502: { code: 'P0502', name: 'Vehicle Speed Sensor Circuit Low Input', description: 'Speed sensor voltage too low.', severity: 'WARNING' },
  P0503: { code: 'P0503', name: 'Vehicle Speed Sensor Intermittent/Erratic/High', description: 'Speed sensor intermittent signal.', severity: 'WARNING' },
  P0504: { code: 'P0504', name: 'Brake Switch A/B Correlation', description: 'Brake switch signals do not match.', severity: 'WARNING' },
  P0505: { code: 'P0505', name: 'Idle Air Control System Malfunction', description: 'Idle control system fault - rough idle likely.', severity: 'WARNING' },
  P0506: { code: 'P0506', name: 'Idle Air Control System RPM Lower Than Expected', description: 'Idle speed too low.', severity: 'WARNING' },
  P0507: { code: 'P0507', name: 'Idle Air Control System RPM Higher Than Expected', description: 'Idle speed too high.', severity: 'WARNING' },
  P0600: { code: 'P0600', name: 'Serial Communication Link Malfunction', description: 'ECU serial communication fault.', severity: 'CRITICAL' },
  P0601: { code: 'P0601', name: 'Internal Control Module Memory Check Sum Error', description: 'ECU memory fault.', severity: 'CRITICAL' },
  P0602: { code: 'P0602', name: 'Control Module Programming Error', description: 'ECU programming error.', severity: 'CRITICAL' },
  P0603: { code: 'P0603', name: 'Internal Control Module Keep Alive Memory (KAM) Error', description: 'ECU keep-alive memory fault.', severity: 'CRITICAL' },
  P0604: { code: 'P0604', name: 'Internal Control Module Random Access Memory (RAM) Error', description: 'ECU RAM fault.', severity: 'CRITICAL' },
  P0605: { code: 'P0605', name: 'Internal Control Module Read Only Memory (ROM) Error', description: 'ECU ROM fault.', severity: 'CRITICAL' },
  P0606: { code: 'P0606', name: 'PCM Processor Fault', description: 'ECU processor fault.', severity: 'CRITICAL' },
  P0607: { code: 'P0607', name: 'Control Module Performance', description: 'ECU performance issue.', severity: 'CRITICAL' },
  P0700: { code: 'P0700', name: 'Transmission Control System Malfunction', description: 'Transmission control general fault.', severity: 'CRITICAL' },
  P0701: { code: 'P0701', name: 'Transmission Control System Range/Performance', description: 'Transmission control out of range.', severity: 'CRITICAL' },
  P0702: { code: 'P0702', name: 'Transmission Control System Electrical', description: 'Transmission control electrical fault.', severity: 'CRITICAL' },
  P0703: { code: 'P0703', name: 'Torque Converter/Brake Switch B Circuit Malfunction', description: 'Brake switch B circuit fault.', severity: 'WARNING' },
  P0704: { code: 'P0704', name: 'Clutch Switch Input Circuit Malfunction', description: 'Clutch switch circuit fault.', severity: 'WARNING' },
  P0705: { code: 'P0705', name: 'Transmission Range Sensor Circuit Malfunction', description: 'Gear selector sensor fault.', severity: 'CRITICAL' },
  P0706: { code: 'P0706', name: 'Transmission Range Sensor Circuit Range/Performance', description: 'Gear range sensor out of range.', severity: 'CRITICAL' },
  P0710: { code: 'P0710', name: 'Transmission Fluid Temperature Sensor Circuit Malfunction', description: 'Transmission fluid temp sensor fault.', severity: 'WARNING' },
  P0715: { code: 'P0715', name: 'Input/Turbine Speed Sensor Circuit Malfunction', description: 'Transmission input speed sensor fault.', severity: 'CRITICAL' },
  P0720: { code: 'P0720', name: 'Output Speed Sensor Circuit Malfunction', description: 'Transmission output speed sensor fault.', severity: 'CRITICAL' },
  P0730: { code: 'P0730', name: 'Incorrect Gear Ratio', description: 'Transmission gear ratio incorrect - may slip.', severity: 'CRITICAL' },
  P0740: { code: 'P0740', name: 'Torque Converter Clutch Circuit Malfunction', description: 'Torque converter clutch fault.', severity: 'CRITICAL' },
  P0750: { code: 'P0750', name: 'Shift Solenoid A Malfunction', description: 'Shift solenoid A fault.', severity: 'CRITICAL' },
  P0755: { code: 'P0755', name: 'Shift Solenoid B Malfunction', description: 'Shift solenoid B fault.', severity: 'CRITICAL' },
  P0760: { code: 'P0760', name: 'Shift Solenoid C Malfunction', description: 'Shift solenoid C fault.', severity: 'CRITICAL' },
  P0765: { code: 'P0765', name: 'Shift Solenoid D Malfunction', description: 'Shift solenoid D fault.', severity: 'CRITICAL' },
  P0770: { code: 'P0770', name: 'Shift Solenoid E Malfunction', description: 'Shift solenoid E fault.', severity: 'CRITICAL' },
  P0780: { code: 'P0780', name: 'Shift Malfunction', description: 'General shift fault in transmission.', severity: 'CRITICAL' },
  P0800: { code: 'P0800', name: 'Transfer Case Control System MIL Request', description: 'Transfer case control fault.', severity: 'WARNING' },
  P0801: { code: 'P0801', name: 'Reverse Inhibit Control Circuit Malfunction', description: 'Reverse inhibit circuit fault.', severity: 'WARNING' },
  P0802: { code: 'P0802', name: 'Transmission Control System MIL Request Circuit Open', description: 'Transmission MIL request circuit open.', severity: 'WARNING' },
  P0803: { code: 'P0803', name: '1-4 Upshift Solenoid Control Circuit Malfunction', description: 'Skip shift solenoid fault.', severity: 'WARNING' },
  P0840: { code: 'P0840', name: 'Transmission Fluid Pressure Sensor/Switch A Circuit Malfunction', description: 'Transmission fluid pressure sensor fault.', severity: 'CRITICAL' },
  P0850: { code: 'P0850', name: 'Park/Neutral Position Switch Input Circuit Malfunction', description: 'Park/neutral switch fault.', severity: 'WARNING' },
  P0853: { code: 'P0853', name: 'Drive Switch Input Circuit Malfunction', description: 'Drive switch circuit fault.', severity: 'WARNING' },
  U0001: { code: 'U0001', name: 'High Speed CAN Communication Bus', description: 'High speed CAN bus communication fault.', severity: 'CRITICAL' },
  U0010: { code: 'U0010', name: 'Medium Speed CAN Communication Bus', description: 'Medium speed CAN bus fault.', severity: 'CRITICAL' },
  U0100: { code: 'U0100', name: 'Lost Communication With ECM/PCM', description: 'Communication lost with engine control module.', severity: 'CRITICAL' },
  U0101: { code: 'U0101', name: 'Lost Communication With TCM', description: 'Communication lost with transmission control module.', severity: 'CRITICAL' },
  U0121: { code: 'U0121', name: 'Lost Communication With ABS Control Module', description: 'ABS module communication fault.', severity: 'CRITICAL' },
  U0140: { code: 'U0140', name: 'Lost Communication With Body Control Module', description: 'Body control module communication fault.', severity: 'WARNING' },
  U0155: { code: 'U0155', name: 'Lost Communication With Instrument Panel Cluster Control Module', description: 'Dashboard cluster communication fault.', severity: 'WARNING' },
  B1000: { code: 'B1000', name: 'ECU Malfunction', description: 'Body control unit general fault.', severity: 'CRITICAL' },
  B1001: { code: 'B1001', name: 'ECU EEPROM Malfunction', description: 'Body ECU EEPROM fault.', severity: 'CRITICAL' },
  C0031: { code: 'C0031', name: 'Right Front Wheel Speed Sensor Circuit', description: 'Right front ABS wheel speed sensor fault.', severity: 'CRITICAL' },
  C0034: { code: 'C0034', name: 'Left Front Wheel Speed Sensor Circuit', description: 'Left front ABS wheel speed sensor fault.', severity: 'CRITICAL' },
  C0037: { code: 'C0037', name: 'Right Rear Wheel Speed Sensor Circuit', description: 'Right rear ABS wheel speed sensor fault.', severity: 'CRITICAL' },
  C0040: { code: 'C0040', name: 'Left Rear Wheel Speed Sensor Circuit', description: 'Left rear ABS wheel speed sensor fault.', severity: 'CRITICAL' },
}

export function localOBD2Lookup(code: string): OBD2CodeEntry | null {
  const upper = code.toUpperCase().trim()
  return OBD2_CODES[upper] || null
}
